language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: xtw0Gp3DpgbFsOJAeWpbMBbNo8ytnyjTpsyany/NnodkCmn5Lzl0MqzdSY78XKyyw/MsaT3Fv6zbbj80AbBCMthtf1rtWJJrcUnUdlA2sS0gjakVHDjdtcWJgNAk440dzZuRZM1j61Us6LUffKM1UbFOdg6opRQWL2Z4W3BWgNFRmpnGtXb6xEdahgmwZ1VqRF9Sjv6C+7/stpfzrt9wLb8Dswdm6oNsbBImJ/oweYLVh0SoFuEPVvRWkJ+4SFXy0Di0RNkxIlbJp2QAcS/xpr6/ro30BvHwzmtptYHEfBluQurrJYFhYKGS1pQWOrU38P8pU/VLDhT+jI2MWAVxlABCGeqmHm3tnoQC3vkVAClN56kpBVg8o+QtT7DjlW5LjUyK9uM3DjzzIgiQakYrvkD2krKxESey8CujELiwInZ/capsTpQJL1kvhJ4yiO8vsSP9UmTdl7Ty9s9tBwsCTzFxo93lSoLHtnfMvikTQThhcL5KHTFTPyTJ7LicDb13Yf0KtbNN0fYeWxTf+zQXst9Kox8FaDLOV/riPkmAvb10zir+1XHf5/qszPUR1o8B5LJDjWCLkc+iDeqdZDswe4izgwJGeNXugR7H1ktNe0dYOqr87s1V+bWveJMqFJ1mEwLq7P1MPBAAZe/jEoUaMq6nc/bS1EaEQ4BCtH54qJ8=
  app: nousfood-api
  on:
    repo: Quanda/nousfood-api
    branch: master
